version: '3.3'
services:
  stellar-hentai-backend:
    container_name: stellar-file-backend
    image: nmluci/stellar:file
    build: 
      context: .
      args:
        USERNAME_GITHUB: nmluci
        TOKEN_GITHUB: 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
    ports:
      - "3020:7780"
      - "3021:7781"
    volumes:
      - /datadrive/stellar-file:/data
volumes:
  cache_data: {}
  mongo_data: {}
  mariadb_data: {}
networks:
  default:
    name: stellar-net
    external: true
    