version: '3.3'
services:
  stellar-hentai-backend:
    container_name: stellar-file-backend
    image: nmluci/stellar:file
    build: 
      context: .
      args:
        USERNAME_GITHUB: nmluci
        TOKEN_GITHUB: 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
    ports:
      - "3020:7780"
      - "3021:7781"
    volumes:
      - /datadrive/stellar-file:/data
  cache_redis:
    container_name: cache_redis
    image: redis:7.0.4
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3001:6379"
    volumes:
      - cache_data:/data
  db_maria:
    image: mariadb:10.8.3
    container_name: db_maria
    environment:
      - MARIADB_ROOT_USERNAME=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=test_db
    ports:
      - "3003:3306"
    restart: unless-stopped
    volumes:
      - mariadb_data:/data
  db_mongo:
    container_name: db_mongo
    image: mongo:4.0.4
    restart: unless-stopped
    ports:
      - "3002:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/data
volumes:
  cache_data: {}
  mongo_data: {}
  mariadb_data: {}
    