version: '3.5'
services:
  stellar-hentai-backend:
    container_name: stellar-file-backend
    image: nmluci/stellar:file
    restart: unless-stopped
    build:
      context: .
      args:
        USERNAME_GITHUB: nmluci
        TOKEN_GITHUB: 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
    ports:
      - "3020:7780"
      - "3021:7781"
    volumes:
      - /datadrive/stellar-file:/data
volumes:
  cache_data: {}
  mongo_data: {}
  mariadb_data: {}
networks:
  default:
    name: stellar-net
    external: true
    